services:
  postgres:
    image: postgres:16-alpine
    container_name: evenue-postgres
    environment:
      POSTGRES_USER: evenue_user
      POSTGRES_PASSWORD: evenue_password
      POSTGRES_DB: evenue_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evenue_user -d evenue_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
